[package]
name = "crypto-utils"
version = "0.3.1"
edition = "2021"
description = "Cryptographic utilities and helpers"
license = "MIT"
repository = "https://github.com/weslien/grit-repo"

[dependencies]
sha2 = "0.10"
rand = "0.8"
base64 = "0.21"
hex = "0.4"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "crypto_benchmarks"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"